language: ruby
rvm:
- 2.1.2
before_deploy:
  - git stash --all
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: bkelly@pivotal.io
  password:
    secure: PsA1Y/gyhnPZYAbnUO4pyhY2L/IF/NdBYVb4n6M0MOprwZfMRD+HdwYSsIDV3Y0LGdeF60IUSTqkMExqLo1f2t6oNLiqIP6seCkSItOjMgigWGIJOMTdI3ZNzemStWZmlZGYg4BynLuclc9lI9hXEv/s4rthN4oGarYh5i+23Zk=
  organization: pivotallabs
  space: pivotal-life
  app: pivotal-life-staging
  on:
    repo: pivotal/pivotal-life
notifications:
  slack:
    secure: B62fOgZnEiQnt2Rx6t8lybSD/cYPQRbotDZ+wU7x/NNSSylWOXywmjuh6nplCYgNYRAniqtZk30dRlCA5+y2jKfdEZ3/CUuaDv0+z0tz4n2Mk084k+DrBI3T4f81k2BCQyAZ8wMdSN7bEEyBOWmeYDzsDCudAARRcK3YHfJAmr8=
